repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.812"
    hooks:
    -   id: mypy
  - repo: https://github.com/psf/black
    rev: "20.8b1"
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
