[tool.poetry]
name = "pyxdu"
version = "0.1.0"
description = "Display the output of \"du\" in a window."
authors = ["Andrey Vlasovskikh <andrey.vlasovskikh@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
docopt = "^0.6.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.1.1"
coverage = "^5.3"

[tool.poetry.scripts]
pyxdu = "pyxdu.__main__:run"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
